__Numpy__

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on array and vectorized operations

In [1]:
!pip install numpy

In [2]:
import numpy as np

## create array using numpu
## create a 1D array

arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:
## 1 d array
arr2= np.array([1,2,3,4,5])
arr2.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array
arr2=np.array([[1, 2, 3, 4, 5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy array
arr = np.array([[1,2,3,], [4,5,6]])

print("Array:\n", arr)
print("Shape", arr.shape)
print("Number of dimension:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape (2, 3)
Number of dimension: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [19]:
## Numpy Vectorize operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Elen=ment wise addition
print("Addition:", arr1+arr2)

## Element wise substraction
print("Substraction:", arr1-arr2)

## Elemenmt wise multiplicatin
print("Multiplication", arr1 * arr2)


Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]


In [20]:
### Universal function
arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## exopential
print(np.exp(arr))

## sine
print(np.sin(arr))

## antural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
## array slicing and Indexing

arr=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
arr[0][0]

np.int64(1)

In [29]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [32]:
print(arr[0][0])
print(arr[0:2,1:])

1
[[2 3 4]
 [6 7 8]]


In [33]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [34]:
arr[1:]=100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [35]:
## statistical concepts -- normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [37]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# mean
mean = np.mean(data)
print("Mean:", mean)

# median
median = np.median(data)
print("Median:", median)

# standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [40]:
## logiucal operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])